### ISSUE TITLE
Clarify jacoco usage and state of arquillian-jacoco usage

### ISSUE THREAD

**Issue by rhusar** [arquillian/arquillian-extension-warp#221]
I don't see any related configuration or instructions how to make this usable from within this project.

Some references to arquillian-jacoco plugin: https://github.com/arquillian/arquillian-extension-jacoco

Also, setup a jacoco coverage step in CI (single matrix combination would suffice).

**Comment by rhusar** [comment]
@WolfgangHG I see you were making some changes to running jacoco at some point, can you elaborate on ^^ ? e.g. how to run a jacoco report?

**Comment by WolfgangHG** [comment]
I have no idea about it ;-). The only change from me was a fix for an error during the build process after dependabot suggested a jacoco update (#103). Would have to do some research what it is and how to use it.

**Comment by rhusar** [comment]
> I have no idea about it ;-). The only change from me was a fix for an error during the build process after dependabot suggested a jacoco update (#103). Would have to do some research what it is and how to use it.

I see, that build is not available anymore, so not sure where it failed. Nevermind, whenever anyone can get to this we will see.

**Comment by WolfgangHG** [comment]
I think it basically broke with one of your Java 11 changes ;-).

Currently, there is this output:

```
[INFO] --- jacoco:0.8.12:prepare-agent (prepare-agent) @ arquillian-warp-jsf-ftest ---
[INFO] argLine set to -javaagent:C:\\Users\\USERNAME\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.12\\org.jacoco.agent-0.8.12-runtime.jar=destfile=C:\\Temp\\github\\arquillian-extension-warp\\extension\\jsf-ftest\\target\\jacoco.exec

...
[INFO] --- jacoco:0.8.12:report (report) @ arquillian-warp-jsf-ftest ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
```

A hint about resolving the latter error is this: https://stackoverflow.com/questions/36304793/jacoco-with-maven-missing-execution-data-file/70928989#70928989

Add "@{argLine}" to the root pom.xml:
```xml
  <build>
    ...
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <configuration>
            <argLine>@{argLine} ${surefire.security.manager} ${modular.jdk.args}</argLine>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
```

This results in an ugly error when building the full package:
<pre>
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "C:\Temp\jdk-11.0.24\bin\java @{argLine} --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED ...
</pre>
"argLine" is not replaced here.

Workaround might be to define a variable "argLine" in root pom.xml like this:
```xml
  <properties>
    ...
    <argLine></argLine>
  </properties>
```
Source: https://stackoverflow.com/questions/23190107/cannot-use-jacoco-jvm-args-and-surefire-jvm-args-together-in-maven/28695766#28695766

Now, Jacoco reports can be found in "arquillian-extension-warp\ftest\target\site\jacoco" and "arquillian-extension-warp\extension\jsf-ftest\target\site\jacoco".
What do you think?

I don't think the reports make sense actually, because the code coverage measures just some utility dummy classes inside the tests. Nothing about coverage of the warp code itself.

**Comment by rhusar** [comment]
@WolfgangHG What commands are you using to run this?

**Comment by WolfgangHG** [comment]
Simply `mvnw clean install -Pwildfly-remote`

The usage of maven wrapper should not have an impact I assume.
The profile "wildfly-remote" should also not make a difference, but I prefer it, because the wildfly output is separated from the build console.

**Comment by rhusar** [comment]
> Simply `mvnw clean install -Pwildfly-remote`
> 
> The usage of maven wrapper should not have an impact I assume. The profile "wildfly-remote" should also not make a difference, but I prefer it, because the wildfly output is separated from the build console.

OK, thanks, I see the report now. The jacoco is only defined for these 2 modules:

./extension/jsf-ftest
./ftest

which I am not sure what's the purpose is. It appears the point is to test jacoco integration as if user would use it - rather than the typical jacoco use case - to evaluate test coverage of the project itself.

**Comment by WolfgangHG** [comment]
That's my understanding, too. It seems to be just a proof of concept, not a real code coverage measurement.

It would probably do no harm to remove Jacoco completely. 

If not: I can send a pull request to fix it (with some comments for the workarounds) this evening.

**Comment by rhusar** [comment]
> That's my understanding, too. It seems to be just a proof of concept, not a real code coverage measurement.
> 
> It would probably do no harm to remove Jacoco completely.
> 
> If not: I can send a pull request to fix it (with some comments for the workarounds) this evening.

I am testing a fix for this to return this to original state as it was before - then we can revisit this for 2.x.

**Comment by rhusar** [comment]
Opened a follow up Issue ^.

For now https://github.com/arquillian/arquillian-extension-warp/pull/228 resolves this one.

**Comment by rhusar** [comment]
Thanks @WolfgangHG for clarifying!
